### ISSUE TITLE
Composer error: Could not find a matching version of package aymanalhattami/filament-audio-video-player.

### ISSUE THREAD

**Issue by dflow** [aymanalhattami/filament-audio-video-player#1]
composer require aymanalhattami/filament-audio-video-player
Info from https://repo.packagist.org: #StandWithUkraine

In PackageDiscoveryTrait.php line 368:

  Could not find a matching version of package aymanalhattami/filament-audio-video-player. Check the packa
  ge spelling, your version constraint and that the package is available in a stability which matches your
   minimum-stability (dev).

**Comment by aymanalhattami** [comment]
I do not work on it right now
